/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *h
 * @author kal bugrara
 */

public class SignupWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;

    public SignupWorkAreaJPanel(Business bs, JPanel jp) {

        business = bs;
        CardSequencePanel = jp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        lblsignup = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        IbIUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        IbIPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister);
        btnRegister.setBounds(310, 290, 100, 23);

        lblsignup.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblsignup.setText("Sign-up");
        add(lblsignup);
        lblsignup.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 290, 100, 23);

        lblName.setText("Name");
        add(lblName);
        lblName.setBounds(210, 90, 70, 17);
        add(txtName);
        txtName.setBounds(290, 90, 120, 23);

        IbIUserName.setText("UserName");
        add(IbIUserName);
        IbIUserName.setBounds(200, 140, 70, 17);
        add(txtUserName);
        txtUserName.setBounds(290, 140, 120, 23);

        IbIPassword.setText("Password");
        add(IbIPassword);
        IbIPassword.setBounds(200, 190, 80, 20);
        add(txtPassword);
        txtPassword.setBounds(290, 190, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
      
        PersonDirectory persondirectory = business.getPersonDirectory();
        Person newPerson = persondirectory.newPerson(txtName.getText());
        StudentDirectory studentdirectory = business.getStudentDirectory();
        StudentProfile stuProfile = studentdirectory.newStudentProfile(newPerson);
        UserAccountDirectory uadirectory = business.getUserAccountDirectory();
        uadirectory.newUserAccount(stuProfile, txtUserName.getText(), txtPassword.getText()); 
        JOptionPane.showMessageDialog(this, "Account successfully added", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbIPassword;
    private javax.swing.JLabel IbIUserName;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblsignup;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

}
