/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author wanyuchiu
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history;
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConscious = new javax.swing.JLabel();
        fieldData = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBloodpressure = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Craete Vital Sign");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        lblDate.setText("Data");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        lblBP.setText("Blood Pressure");
        add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lblConscious.setText("Conscious Status");
        add(lblConscious, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));
        add(fieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 130, 30));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 130, 30));
        add(fieldBloodpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 130, 30));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 130, 30));

        buttonGroup1.add(btnYes);
        btnYes.setSelected(true);
        btnYes.setText("Yes");
        add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        buttonGroup1.add(btnNo);
        btnNo.setText("No");
        add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       
       //Step 1: collect text from the field
       String data = fieldData.getText();
       float temp = Float.parseFloat(fieldTemperature.getText()); //use parseFloat to change Float to String
       double bp = Double.parseDouble(fieldBloodpressure.getText());//use parseDouble to change Float to String
       int pulse = Integer.parseInt(fieldPulse.getText());//use parseInt to change Integer to String
       boolean isConcious;
       
       if(btnYes.isSelected()){
           isConcious = true;  
       }
       else{
           isConcious = false;  
       }
       
       //Step 2: put those information to product
       VitalSign vs = history.addNewVital();
       vs.setData(data);
       vs.setTemperature(temp);
       vs.setBloodpressure(bp);
       vs.setPulse(pulse);
       vs.setIsConcious(isConcious);
       
       //step 3 : pop up messsage and claer typed text
       JOptionPane.showMessageDialog(this," New VitalSign Added ","Success",JOptionPane.INFORMATION_MESSAGE);
       
       fieldData.setText("");
       fieldTemperature.setText("");
       fieldBloodpressure.setText("");
       fieldPulse.setText("");
       
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldBloodpressure;
    private javax.swing.JTextField fieldData;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblConscious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
