/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wanyuchiu
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    VitalSignHistory history;
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh; 
        populateTable();
    }
    
    private void populateTable(){
        
        //Table Variable
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        
        //Intiallize Table
        model.setRowCount(0);
        
        //data put in table and display one by one
        for(VitalSign vs: history.getHistory()){
            
            //Object array for five object data
            Object[] row = new Object[5];
            row[0] = vs;//data is not a object but a string，so use override
            row[1] = vs.getTemperature();
            row[2] = vs.getBloodpressure();
            row[3] = vs.getPulse();
            row[4] = vs.isIsConcious(); // use is not get for boolean
            
            //add row
            model.addRow(row);
        }
        
        //select row to view information
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVital = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConscious = new javax.swing.JLabel();
        fieldData = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBloodpressure = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Temperature", "Blood Pressure", "Pulse", "Concious Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVital);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 520, 190));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblTitle.setText("View Vital Sign History");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        lblDate.setText("Data");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 30, -1));

        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 70, -1));

        lblBP.setText("Blood Pressure");
        add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 90, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 30, -1));

        lblConscious.setText("Conscious Status");
        add(lblConscious, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 100, -1));
        add(fieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 130, 30));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 130, 30));
        add(fieldBloodpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 130, 30));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 130, 30));
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        //select index value
        int selectedRow = tblVital.getSelectedRow();
        
        //validation
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(jScrollPane1, "Please select a row to delete ", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        //get the model, default table model,select which label
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        VitalSign selectedVital = (VitalSign) model.getValueAt(selectedRow, 0);//select Object not a String
        
        //delete 
        history.deleteVital(selectedVital);
        
        JOptionPane.showMessageDialog(jScrollPane1, "Vital Sign deleted ", "Successs", JOptionPane.WARNING_MESSAGE);
        
        //refresh table
        populateTable();
        
        //claer typed text
        fieldData.setText("");
        fieldTemperature.setText("");
        fieldBloodpressure.setText("");
        fieldPulse.setText("");
        lblStatus.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        //select index value
        int selectedRow = tblVital.getSelectedRow();
        
        //validation
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(jScrollPane1, "Please select a row to view ", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        //get the model, default table model
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        VitalSign selectedVital = (VitalSign) model.getValueAt(selectedRow, 0);//select Object not a String
        
        if (selectedVital != null){
            
            fieldData.setText(selectedVital.getData());
            fieldTemperature.setText(String.valueOf(selectedVital.getTemperature()));//change type into string
            fieldBloodpressure.setText(String.valueOf(selectedVital.getBloodpressure()));
            fieldPulse.setText(String.valueOf(selectedVital.getPulse()));
            
            if(selectedVital.isIsConcious()){
                lblStatus.setText("Yes");
            }
            else{
                lblStatus.setText("No");
            }
          
            
        }
        
        
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fieldBloodpressure;
    private javax.swing.JTextField fieldData;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblConscious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblVital;
    // End of variables declaration//GEN-END:variables
}
