/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author wanyuchiu
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    public CreateJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        IbIDescription = new javax.swing.JLabel();
        fieldDescription = new javax.swing.JTextField();
        fieldAvailability = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        fieldPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMenuStreet = new javax.swing.JLabel();
        lblManuUnit = new javax.swing.JLabel();
        lblManuCity = new javax.swing.JLabel();
        lblManuZipcode = new javax.swing.JLabel();
        fieldManuStreet = new javax.swing.JTextField();
        fieldManuUnit = new javax.swing.JTextField();
        fieldManuCity = new javax.swing.JTextField();
        fieldManuZipcode = new javax.swing.JTextField();
        lblShippingStreet = new javax.swing.JLabel();
        fieldShippingStreet = new javax.swing.JTextField();
        lblShippingUnit = new javax.swing.JLabel();
        fieldShippingUnit = new javax.swing.JTextField();
        lblShippingCity = new javax.swing.JLabel();
        fieldShippingCity = new javax.swing.JTextField();
        lblShippingZipcode = new javax.swing.JLabel();
        fieldShippingZipcode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Create a Product");

        lblName.setText("Name");

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        IbIDescription.setText("Discription");

        fieldDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescriptionActionPerformed(evt);
            }
        });

        fieldAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAvailabilityActionPerformed(evt);
            }
        });

        lblAvailability.setText("Availability");

        lblPrice.setText("Price");

        fieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPriceActionPerformed(evt);
            }
        });

        jLabel1.setText("Manufacture Address");

        jLabel3.setText("Shipping Address");

        lblMenuStreet.setText("Street Name");

        lblManuUnit.setText("Unit Number");

        lblManuCity.setText("City");

        lblManuZipcode.setText("Zip Code");

        fieldManuStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuStreetActionPerformed(evt);
            }
        });

        fieldManuUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuUnitActionPerformed(evt);
            }
        });

        fieldManuCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuCityActionPerformed(evt);
            }
        });

        lblShippingStreet.setText("Street Name");

        fieldShippingStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingStreetActionPerformed(evt);
            }
        });

        lblShippingUnit.setText("Unit Number");

        fieldShippingUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingUnitActionPerformed(evt);
            }
        });

        lblShippingCity.setText("City");

        fieldShippingCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingCityActionPerformed(evt);
            }
        });

        lblShippingZipcode.setText("Zip Code");

        fieldShippingZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingZipcodeActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblManuZipcode)
                            .addComponent(lblManuCity)
                            .addComponent(lblManuUnit)
                            .addComponent(lblMenuStreet))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldManuZipcode)
                            .addComponent(fieldManuCity)
                            .addComponent(fieldManuUnit)
                            .addComponent(fieldManuStreet)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblName)
                                    .addGap(28, 28, 28))
                                .addComponent(lblAvailability, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(IbIDescription, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblShippingUnit))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblShippingStreet)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54))
                            .addComponent(fieldShippingUnit)
                            .addComponent(fieldShippingStreet)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblShippingCity)
                            .addComponent(lblShippingZipcode))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldShippingCity)
                            .addComponent(fieldShippingZipcode)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblTitle)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IbIDescription))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(fieldAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenuStreet)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldShippingStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblShippingStreet))
                    .addComponent(fieldManuStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblManuUnit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblShippingUnit)
                        .addComponent(fieldShippingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldManuUnit))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldManuCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblManuCity))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldShippingCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblShippingCity)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShippingZipcode)
                    .addComponent(fieldShippingZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldManuZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManuZipcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAvailabilityActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescriptionActionPerformed

    private void fieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPriceActionPerformed

    private void fieldManuStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuStreetActionPerformed

    private void fieldManuUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuUnitActionPerformed

    private void fieldManuCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuCityActionPerformed

    private void fieldShippingStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingStreetActionPerformed

    private void fieldShippingUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingUnitActionPerformed

    private void fieldShippingCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingCityActionPerformed

    private void fieldShippingZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingZipcodeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        //Step 1: collect text from the field
        String name = fieldName.getText();
        String description = fieldDescription.getText();
        String avail = fieldAvailability.getText();
        String price = fieldPrice.getText();
        
        String manuStreet = fieldManuStreet.getText();
        String manuUnit = fieldManuUnit.getText();
        String manuCity = fieldManuCity.getText();
        String manuZipCode = fieldManuZipcode.getText();
        
        String shippingStreet = fieldShippingStreet.getText();
        String shippingUnit = fieldShippingUnit.getText();
        String shippingCity = fieldShippingCity.getText();
        String shippingZipCode = fieldShippingZipcode.getText();
        
        //Step 2: put those information to product
        product.setName(name);
        product.setDescription(description);
        product.setAvailNum(avail);
        product.setPrice(price);
        
        product.getManufactureAddress().setStreetname(manuStreet);
        product.getManufactureAddress().setUnitNum(manuUnit);
        product.getManufactureAddress().setCity(manuCity);
        product.getManufactureAddress().setZipcode(manuZipCode);
        
        
        product.getShippingAddress().setStreetname(shippingStreet);
        product.getShippingAddress().setUnitNum(shippingUnit);
        product.getShippingAddress().setCity(shippingCity);
        product.getShippingAddress().setZipcode(shippingZipCode);
        
        //step 3:
        JOptionPane.showMessageDialog(this,"Successfully Saved!");
        
        fieldName.setText("");
        fieldDescription.setText("");
        fieldAvailability.setText("");
        fieldPrice.setText("");
        fieldManuStreet.setText("");
        fieldManuUnit.setText("");
        fieldManuCity.setText("");
        fieldManuZipcode.setText("");
        fieldShippingStreet.setText("");
        fieldShippingUnit.setText("");
        fieldShippingCity.setText("");
        fieldShippingZipcode.setText("");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbIDescription;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAvailability;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldManuCity;
    private javax.swing.JTextField fieldManuStreet;
    private javax.swing.JTextField fieldManuUnit;
    private javax.swing.JTextField fieldManuZipcode;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreet;
    private javax.swing.JTextField fieldShippingUnit;
    private javax.swing.JTextField fieldShippingZipcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblManuCity;
    private javax.swing.JLabel lblManuUnit;
    private javax.swing.JLabel lblManuZipcode;
    private javax.swing.JLabel lblMenuStreet;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreet;
    private javax.swing.JLabel lblShippingUnit;
    private javax.swing.JLabel lblShippingZipcode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
